CREATE TABLE IF NOT EXISTS PRODUTO (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    preco DOUBLE NOT NULL,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR (50) NOT NULL,
    estoque INTEGER NOT NULL   
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    id INTEGER NOT NULL PRIMARY KEY,
    preco DOUBLE NOT NULL,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR (50) NOT NULL,
    estoque INTEGER NOT NULL   
);
