CREATE TABLE IF NOT EXISTS PRODUTO (
    id SERIAL,    
    nome VARCHAR(50) NOT NULL,
    preco DOUBLE NOT NULL,
    descricao VARCHAR (50) NOT NULL,
    estoque INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    id SERIAL,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR (50) NOT NULL,
    tipo BOOLEAN NOT NULL,
    PRIMARY KEY(id)
);
